package dev.alllexey.itmowidgets.buildlogic.strings

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.w3c.dom.Element
import java.io.File
import javax.xml.parsers.DocumentBuilderFactory

/**
 * The `key -> R` table of the exported strings (ADR 0028, L07 KM-07): `UiText.Res` and `UiText.Plural` carry a CMP
 * resource whose `key` is the Android resource name, and the Android resolver turns it into `R.string.<key>` or
 * `R.plurals.<key>` through this table instead of `Resources.getIdentifier`.
 */
object AndroidStringIds {

    const val OBJECT_NAME = "ExportedStringIds"

    /** The string and plural names of every `values*` file under [resDir], each sorted and distinct. */
    fun keys(resDir: File): Keys {
        val files = resDir.listFiles { dir -> dir.isDirectory && dir.name.startsWith("values") }.orEmpty()
            .flatMap { dir -> dir.listFiles { file -> file.extension == "xml" }.orEmpty().toList() }
        val entries = files.flatMap { file -> entries(file) }
        fun names(kind: String) = entries.filter { it.first == kind }.map { it.second }.distinct().sorted()
        return Keys(strings = names("string"), plurals = names("plurals"))
    }

    /** `<package>/ExportedStringIds.kt`: one `when` per resource type, unknown keys fail with the key. */
    fun render(appNamespace: String, packageName: String, keys: Keys): String = buildString {
        appendLine("// Generated by itmowidgets.strings from the androidExport files of the shared modules; do not edit.")
        appendLine("package $packageName")
        appendLine()
        appendLine("import $appNamespace.R")
        appendLine()
        appendLine("/** `StringResource.key` -> `R.string` and `PluralStringResource.key` -> `R.plurals` (ADR 0028). */")
        appendLine("internal object $OBJECT_NAME {")
        appendFunction("string", "string", keys.strings)
        appendFunction("plural", "plurals", keys.plurals)
        appendLine("}")
    }

    private fun StringBuilder.appendFunction(name: String, type: String, names: List<String>) {
        appendLine()
        appendLine("    fun $name(key: String): Int = when (key) {")
        names.forEach { appendLine("        \"$it\" -> R.$type.$it") }
        appendLine("        else -> throw IllegalArgumentException(")
        appendLine("            \"No exported $type \\\"\$key\\\"; is its file named in an androidExport line?\"")
        appendLine("        )")
        appendLine("    }")
    }

    private fun entries(file: File): List<Pair<String, String>> {
        val root = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(file).documentElement
        val nodes = root.childNodes
        return (0 until nodes.length).map { nodes.item(it) }.filterIsInstance<Element>()
            .filter { it.tagName == "string" || it.tagName == "plurals" }
            .map { it.tagName to it.getAttribute("name") }
    }

    data class Keys(val strings: List<String>, val plurals: List<String>)
}

/** Writes [AndroidStringIds] for one `:app` variant from its merged exports. */
abstract class GenerateAndroidStringIds : DefaultTask() {

    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val exportedRes: DirectoryProperty

    @get:Input
    abstract val appNamespace: Property<String>

    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val out = outputDir.get().asFile
        out.deleteRecursively()
        val target = File(out, packageName.get().replace('.', '/') + "/${AndroidStringIds.OBJECT_NAME}.kt")
        target.parentFile.mkdirs()
        val keys = AndroidStringIds.keys(exportedRes.get().asFile)
        target.writeText(AndroidStringIds.render(appNamespace.get(), packageName.get(), keys))
    }
}
