// Core 2.0, the typed Backend client (L19). itmowidgets.kmp.library brings kotlinx.serialization
// (recipe kmp-module-build-file).
plugins {
    id("itmowidgets.kmp.library")
}

// Host and simulator tests read their resources by absolute path through okio's FileSystem.SYSTEM: neither the
// Android host test classpath nor a Kotlin/Native test binary carries src/commonTest/resources.
val testResourcesDir: String = layout.projectDirectory.dir("src/commonTest/resources").asFile.absolutePath
val generateTestResourcesDir = tasks.register("generateTestResourcesDir") {
    description = "Generates TEST_RESOURCES_DIR, the absolute path of src/commonTest/resources, for commonTest."
    val directory = testResourcesDir
    val output = layout.buildDirectory.dir("generated/backendClient/commonTest/kotlin")
    inputs.property("directory", directory)
    outputs.dir(output)
    doLast {
        val file = output.get().file("dev/alllexey/itmowidgets/client/support/TestResourcesDir.kt").asFile
        file.parentFile.mkdirs()
        val literal = directory.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
        file.writeText(
            """
            |// Generated by generateTestResourcesDir (shared/backend-client/build.gradle.kts), do not edit.
            |package dev.alllexey.itmowidgets.client.support
            |
            |/** The absolute path of this module's src/commonTest/resources. */
            |const val TEST_RESOURCES_DIR: String = "$literal"
            |
            """.trimMargin(),
        )
    }
}

// AGP's host-test lint tasks read the commonTest source dirs as plain files, so the srcDir provider's task dependency
// below never reaches them; :app:lintGithubDebug (checkDependencies) runs them, and Gradle rejects the implicit use.
tasks.named { it.contains("AndroidHostTest") && it.contains("Lint", ignoreCase = true) }.configureEach {
    dependsOn(generateTestResourcesDir)
}

kotlin {
    sourceSets {
        // No Ktor engine artifact: the caller passes the engine (OkHttp on Android, Darwin on iOS, ADR 0026).
        commonMain.dependencies {
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
        }
        commonTest {
            kotlin.srcDir(generateTestResourcesDir)
            dependencies {
                implementation(libs.ktor.client.mock)
                implementation(libs.okio)
            }
        }
    }
}
