package dev.alllexey.itmowidgets.client.support

import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

/**
 * Reads checked-in test resources by absolute path ([TEST_RESOURCES_DIR], generated by the build file), the same way
 * on the Android host and the iOS simulator. A path is relative to `src/commonTest/resources`, for example
 * `support/sample.json`.
 */
object Fixtures {
    private val root = TEST_RESOURCES_DIR.toPath()

    fun read(path: String): String = FileSystem.SYSTEM.read(root.resolve(path, normalize = true)) { readUtf8() }
}
