#!/usr/bin/env python3
"""gen-tokens.py [--check]    design tokens -> iosApp/Sources/DesignSystem/Tokens.generated.swift (L18 IO-06a)

Reads shared/designsystem/tokens/itmo-tokens.json (L08 DS-01b, generated by
`:shared:designsystem:exportDesignTokens`) and writes the Swift side of the tokens: the static light and dark colour
schemes and extended colours (ItmoColorRoles, ItmoExtendedColorRoles, the dynamic ItmoColor), the corner scale and
named shapes, spacing, the type roles as Dynamic Type text styles, and motion. docs/ios.md, Design system.

- Refuses a schemaVersion it does not know, a colour that is not #RRGGBB, a type role without a text style below,
  a font family other than the system font and a weight off the table below; it never guesses.
- Type roles map onto Dynamic Type text styles (the nearest default size at Large), never onto fixed sizes; the
  weights come from the tokens. Line height and tracking stay the text style's own.
- dp and sp become points 1:1; durations become seconds. Derived colours stay with the feature that needs them.
- --check: writes nothing; exits 1 when the committed file differs from what the tokens give
  (scripts/ios/check-tokens.sh runs it inside scripts/ios/test.sh).
- Exit code: 0 written or fresh, 1 stale (--check), 2 refused (bad tokens, usage).
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOKENS = ROOT / "shared/designsystem/tokens/itmo-tokens.json"
OUTPUT = ROOT / "iosApp/Sources/DesignSystem/Tokens.generated.swift"
FIX = "python3 scripts/ios/gen-tokens.py"

SCHEMA_VERSIONS = {1}

# M3 type role -> the Dynamic Type text style whose default size at Large is the nearest to the role's size
# (largeTitle 34, title 28, title2 22, title3 20, body 17, callout 16, subheadline 15, footnote 13, caption 12,
# caption2 11). The display roles have no larger style and scale as largeTitle.
TEXT_STYLES = {
    "displayLarge": "largeTitle",
    "displayMedium": "largeTitle",
    "displaySmall": "largeTitle",
    "headlineLarge": "largeTitle",
    "headlineMedium": "title",
    "headlineSmall": "title2",
    "titleLarge": "title2",
    "titleMedium": "callout",
    "titleSmall": "subheadline",
    "bodyLarge": "body",
    "bodyMedium": "subheadline",
    "bodySmall": "footnote",
    "labelLarge": "subheadline",
    "labelMedium": "caption",
    "labelSmall": "caption2",
}

WEIGHTS = {400: "regular", 500: "medium", 600: "semibold", 700: "bold"}

HEX = re.compile(r"#([0-9A-Fa-f]{6})")
IDENTIFIER = re.compile(r"[a-z][A-Za-z0-9]*")


class Refused(Exception):
    pass


def require(condition, message):
    if not condition:
        raise Refused(message)


def identifier(name, where):
    require(IDENTIFIER.fullmatch(name), f"{where}: '{name}' is not a lowerCamelCase name")
    return name


def rgb(value, where):
    match = HEX.fullmatch(value) if isinstance(value, str) else None
    require(match, f"{where}: '{value}' is not #RRGGBB")
    return "0x" + match.group(1).upper()


def number(value, where):
    require(isinstance(value, (int, float)) and not isinstance(value, bool), f"{where}: '{value}' is not a number")
    text = repr(float(value))
    return text[:-2] if text.endswith(".0") else text


def roles(section, where):
    require(isinstance(section, dict) and section, f"{where}: missing")
    light, dark = section.get("light"), section.get("dark")
    require(isinstance(light, dict) and isinstance(dark, dict), f"{where}: needs light and dark")
    require(list(light) == list(dark), f"{where}: light and dark list different roles")
    return [(identifier(name, where), rgb(light[name], f"{where}.light.{name}"), rgb(dark[name], f"{where}.dark.{name}"))
            for name in light]


def numbers(section, where, skip=()):
    require(isinstance(section, dict) and section, f"{where}: missing")
    return [(identifier(name, where), number(value, f"{where}.{name}"))
            for name, value in section.items() if name not in skip]


def colour_block(type_name, doc, entries):
    lines = [f"/// {doc}", f"struct {type_name}: Sendable {{"]
    lines += [f"    let {name}: UInt32" for name, _, _ in entries]
    lines += ["}", "", f"extension {type_name} {{"]
    for scheme, index in (("light", 1), ("dark", 2)):
        lines.append(f"    static let {scheme} = {type_name}(")
        lines += [f"        {entry[0]}: {entry[index]}," for entry in entries]
        lines[-1] = lines[-1].rstrip(",")
        lines.append("    )")
    lines.append("}")
    return lines


def constants(type_name, doc, entries, unit="CGFloat"):
    lines = [f"/// {doc}", f"enum {type_name} {{"]
    lines += [f"    static let {name}: {unit} = {value}" for name, value in entries]
    lines.append("}")
    return lines


def generate(tokens):
    version = tokens.get("schemaVersion")
    require(version in SCHEMA_VERSIONS,
            f"schemaVersion {version!r} is unknown (this generator reads {sorted(SCHEMA_VERSIONS)}); "
            "update scripts/ios/gen-tokens.py with the new schema")

    colour = tokens.get("color", {})
    scheme = roles(colour.get("scheme"), "color.scheme")
    extended = roles(colour.get("extended"), "color.extended")
    clash = {name for name, _, _ in scheme} & {name for name, _, _ in extended}
    require(not clash, f"color: {sorted(clash)} are both scheme and extended roles")

    shape = tokens.get("shape", {})
    corner = shape.get("corner", {})
    require(corner.get("full") == "50%", "shape.corner.full: expected '50%' (Capsule on iOS)")
    corners = numbers(corner, "shape.corner", skip=("full",))
    named = numbers(shape.get("named"), "shape.named")
    spacing = numbers(tokens.get("spacing"), "spacing")

    type_tokens = tokens.get("type", {})
    require(type_tokens.get("fontFamily") == "system", "type.fontFamily: only the system font is supported")
    regular, emphasized = type_tokens.get("roles"), type_tokens.get("emphasized")
    require(isinstance(regular, dict) and regular, "type.roles: missing")
    require(isinstance(emphasized, dict) and list(emphasized) == list(regular),
            "type.emphasized: must list the same roles as type.roles")
    type_roles = []
    for name in regular:
        identifier(name, "type.roles")
        require(name in TEXT_STYLES, f"type.roles.{name}: no Dynamic Type text style; add it to TEXT_STYLES")
        weights = []
        for table, label in ((regular, "roles"), (emphasized, "emphasized")):
            weight = table[name].get("weight")
            require(weight in WEIGHTS, f"type.{label}.{name}.weight: {weight!r} is not one of {sorted(WEIGHTS)}")
            weights.append(WEIGHTS[weight])
        type_roles.append((name, TEXT_STYLES[name], *weights))

    motion = tokens.get("motion", {})
    milliseconds = motion.get("durationMs")
    require(isinstance(milliseconds, dict) and milliseconds, "motion.durationMs: missing")
    durations = []
    for name, value in milliseconds.items():
        number(value, f"motion.durationMs.{name}")
        durations.append((identifier(name, "motion.durationMs"), number(value / 1000, f"motion.durationMs.{name}")))
    easing = motion.get("easing")
    require(isinstance(easing, list) and len(easing) == 4, "motion.easing: expected four control points")
    easing = [number(value, "motion.easing") for value in easing]
    pulse_min_alpha = number(motion.get("pulseMinAlpha"), "motion.pulseMinAlpha")

    out = [
        "// Generated from shared/designsystem/tokens/itmo-tokens.json by scripts/ios/gen-tokens.py; do not edit.",
        f"// Regenerate with `{FIX}`; scripts/ios/check-tokens.sh fails while this file is stale.",
        "",
        "import SwiftUI",
        "",
        "/// The token schema this file was generated from.",
        f"let itmoTokensSchemaVersion = {version}",
        "",
    ]
    out += colour_block("ItmoColorRoles", "The static M3 colour roles, light and dark; `ItmoColor` picks one by the colour scheme.",
                        scheme)
    out.append("")
    out += colour_block("ItmoExtendedColorRoles",
                        "The app's own colours beside the scheme, light and dark.",
                        extended)
    out += ["", "/// Every role as a `Color` that follows the colour scheme of its environment.", "enum ItmoColor {"]
    out += [f"    static let {name} = Color(itmo: \\ItmoColorRoles.{name})" for name, _, _ in scheme]
    out += [f"    static let {name} = Color(itmo: \\ItmoExtendedColorRoles.{name})" for name, _, _ in extended]
    out += ["}", ""]
    out += constants("ItmoCorner", "The corner scale in points; `full` is a `Capsule`.", corners)
    out.append("")
    out += constants("ItmoShapes", "The named card and group shapes in points.", named)
    out.append("")
    out += constants("ItmoSpacing", "Spacing in points.", spacing)
    out += ["", "/// The M3 type roles. Each is a Dynamic Type text style with the role's weight, never a fixed size.",
            "enum ItmoTypeRole: CaseIterable, Sendable {"]
    out += [f"    case {name}" for name, *_ in type_roles]
    out += ["", "    var textStyle: Font.TextStyle {", "        switch self {"]
    out += [f"        case .{name}: .{style}" for name, style, _, _ in type_roles]
    out += ["        }", "    }", "", "    var weight: Font.Weight {", "        switch self {"]
    out += [f"        case .{name}: .{weight}" for name, _, weight, _ in type_roles]
    out += ["        }", "    }", "", "    var emphasizedWeight: Font.Weight {", "        switch self {"]
    out += [f"        case .{name}: .{weight}" for name, _, _, weight in type_roles]
    out += ["        }", "    }", "}", ""]
    out += ["/// Durations in seconds, the easing of the kit animations and the skeleton pulse.", "enum ItmoMotion {"]
    out += [f"    static let {name}: TimeInterval = {value}" for name, value in durations]
    out += [f"    static let pulseMinAlpha: Double = {pulse_min_alpha}"]
    out += ["", "    /// The cubic Bezier easing `(x1, y1, x2, y2)` of every kit animation.",
            f"    static let easing: (x1: Double, y1: Double, x2: Double, y2: Double) = ({', '.join(easing)})"]
    out += ["}"]
    return "\n".join(out) + "\n"


def main(argv):
    check = argv == ["--check"]
    if argv and not check:
        print(__doc__.strip().splitlines()[0], file=sys.stderr)
        return 2
    try:
        text = generate(json.loads(TOKENS.read_text(encoding="utf-8")))
    except (OSError, ValueError, Refused) as problem:
        print(f"gen-tokens.py: {TOKENS.relative_to(ROOT)}: {problem}", file=sys.stderr)
        return 2
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if check:
        if current != text:
            print(f"gen-tokens.py: {OUTPUT.relative_to(ROOT)} is stale; run {FIX}", file=sys.stderr)
            return 1
        return 0
    if current != text:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(text, encoding="utf-8")
        print(f"gen-tokens.py: wrote {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
