// Generated from docs/design/icons.tsv by `scripts/verify.sh run -- :app:exportAppleStrings`; do not edit.

/// The icon registry on SwiftUI and system surfaces.
enum AppSymbol: String, CaseIterable {
    case accountCircle = "account_circle"
    case accountCircleFilled = "account_circle_filled"
    case add = "add"
    case arrowBack = "arrow_back"
    case arrowDropDown = "arrow_drop_down"
    case arrowDropUp = "arrow_drop_up"
    case assignment = "assignment"
    case autoAwesome = "auto_awesome"
    case brandGithub = "brand_github"
    case brandTelegram = "brand_telegram"
    case brandVk = "brand_vk"
    case calendarAdd = "calendar_add"
    case chat = "chat"
    case check = "check"
    case checkCircle = "check_circle"
    case chevronLeft = "chevron_left"
    case chevronRight = "chevron_right"
    case clock = "clock"
    case close = "close"
    case codeBlocks = "code_blocks"
    case computer = "computer"
    case contentCopy = "content_copy"
    case delete = "delete"
    case download = "download"
    case edit = "edit"
    case editCalendar = "edit_calendar"
    case editNote = "edit_note"
    case error = "error"
    case eventNote = "event_note"
    case exercise = "exercise"
    case exerciseFilled = "exercise_filled"
    case expandMore = "expand_more"
    case flag = "flag"
    case folder = "folder"
    case formatListNumbered = "format_list_numbered"
    case globe = "globe"
    case group = "group"
    case history = "history"
    case home = "home"
    case homeFilled = "home_filled"
    case howToReg = "how_to_reg"
    case info = "info"
    case keep = "keep"
    case keepOff = "keep_off"
    case keyboardArrowUp = "keyboard_arrow_up"
    case language = "language"
    case link = "link"
    case locationOn = "location_on"
    case lock = "lock"
    case login = "login"
    case logout = "logout"
    case menuBook = "menu_book"
    case menuBookFilled = "menu_book_filled"
    case moreVert = "more_vert"
    case notification = "notification"
    case openInNew = "open_in_new"
    case person = "person"
    case pin = "pin"
    case qrCode = "qr_code"
    case qrCodeScanner = "qr_code_scanner"
    case refresh = "refresh"
    case remove = "remove"
    case schedule = "schedule"
    case scheduleFilled = "schedule_filled"
    case school = "school"
    case search = "search"
    case settings = "settings"
    case share = "share"
    case starShine = "star_shine"
    case summaryCollapse = "summary_collapse"
    case summaryExpand = "summary_expand"
    case table = "table"
    case videocam = "videocam"
    case widgets = "widgets"
    case work = "work"

    /// The SF Symbol name, or the asset name of a custom symbol image when `isCustom`.
    var systemName: String {
        switch self {
        case .accountCircle: "person.crop.circle"
        case .accountCircleFilled: "person.crop.circle.fill"
        case .add: "plus"
        case .arrowBack: "chevron.backward"
        case .arrowDropDown: "arrowtriangle.down.fill"
        case .arrowDropUp: "arrowtriangle.up.fill"
        case .assignment: "doc.text"
        case .autoAwesome: "sparkles"
        case .brandGithub: "custom.brand_github"
        case .brandTelegram: "custom.brand_telegram"
        case .brandVk: "custom.brand_vk"
        case .calendarAdd: "calendar.badge.plus"
        case .chat: "bubble.left"
        case .check: "checkmark"
        case .checkCircle: "checkmark.circle"
        case .chevronLeft: "chevron.left"
        case .chevronRight: "chevron.right"
        case .clock: "clock.fill"
        case .close: "xmark"
        case .codeBlocks: "chevron.left.forwardslash.chevron.right"
        case .computer: "desktopcomputer"
        case .contentCopy: "doc.on.doc"
        case .delete: "trash"
        case .download: "arrow.down.to.line"
        case .edit: "pencil"
        case .editCalendar: "calendar"
        case .editNote: "square.and.pencil"
        case .error: "exclamationmark.circle"
        case .eventNote: "calendar.day.timeline.left"
        case .exercise: "dumbbell"
        case .exerciseFilled: "dumbbell.fill"
        case .expandMore: "chevron.down"
        case .flag: "flag"
        case .folder: "folder"
        case .formatListNumbered: "list.number"
        case .globe: "globe"
        case .group: "person.2"
        case .history: "clock.arrow.circlepath"
        case .home: "house"
        case .homeFilled: "house.fill"
        case .howToReg: "person.crop.circle.badge.checkmark"
        case .info: "info.circle"
        case .keep: "pin"
        case .keepOff: "pin.slash"
        case .keyboardArrowUp: "chevron.up"
        case .language: "network"
        case .link: "link"
        case .locationOn: "mappin.and.ellipse"
        case .lock: "lock"
        case .login: "arrow.right.to.line"
        case .logout: "rectangle.portrait.and.arrow.right"
        case .menuBook: "book"
        case .menuBookFilled: "book.fill"
        case .moreVert: "ellipsis"
        case .notification: "bell"
        case .openInNew: "arrow.up.right.square"
        case .person: "person"
        case .pin: "pin"
        case .qrCode: "qrcode"
        case .qrCodeScanner: "qrcode.viewfinder"
        case .refresh: "arrow.clockwise"
        case .remove: "minus"
        case .schedule: "clock"
        case .scheduleFilled: "clock.fill"
        case .school: "graduationcap"
        case .search: "magnifyingglass"
        case .settings: "gearshape"
        case .share: "square.and.arrow.up"
        case .starShine: "sparkle"
        case .summaryCollapse: "chevron.up"
        case .summaryExpand: "chevron.down"
        case .table: "tablecells"
        case .videocam: "video"
        case .widgets: "square.grid.2x2"
        case .work: "briefcase"
        }
    }

    /// Custom symbols load with `UIImage(named:)` and `Image(_:)`, not with `systemName:`.
    var isCustom: Bool {
        systemName.hasPrefix("custom.")
    }
}
