#!/bin/bash
# integrate list <repo>
# integrate merge <repo> <pr> [--local-verify <log>]
# integrate revert <repo> <sha> <reason>
# integrate batch <repo> [--window 14|19] [--apk <file> | --build-apk]
# integrate ready [--dry-run] [--lanes <dir>]
#   common options: --pr-json <file> (PR data from a file instead of `gh pr list/view`;
#   tests and offline runs; close and comment still call gh), --board <file>
#
# ITMO.Widgets v2.3 (L01 G-13a). The integrator's merge tool. It works only in the
# integrator worktree ~/proj/.wt/<repo>/next (marker `integrator`, `lane next <repo>`)
# and pushes only refs/heads/v2.3/next there; protected refs move through `promote`.
#
#   repo  android | backend | myitmoapi | web (core has no v2.3/next; L01-CF PRs into
#         core master, like PRs into release/*, go to promote)
#
# list    open PRs into v2.3/next: item IDs from the title, head CI, changed paths vs the
#         body's `Surface:` globs, size (changed lines, renames aside; > 1500 flagged),
#         master section 6 hot files touched, queue length (section 4.5 stop above 10).
# merge   base v2.3/next only; head v2.3/<lane>/<slug> (title `<ID>[, <ID>]: <summary>`)
#         or, in android only, dependabot/* by dependabot (surface = build files,
#         refused while an L04 PR touching build files is open, commit
#         `TC-08: <title> (#<n>)`); CI green on the head (no check runs: --local-verify
#         <log> ending `VERIFY <R> <mode> PASS ... <head sha7>` plus a PASS `Verify:` line
#         in the body); every changed path inside `Surface:` unless a PR comment starts
#         with "surface OK". Squash onto fresh origin/v2.3/next, commit `<title> (#<n>)`,
#         push, close the PR with "Squash-merged into v2.3/next as <sha>", board rows of
#         the title's IDs -> merged. A conflict aborts, comments "rebase on v2.3/next"
#         and leaves the PR open.
# revert  `git revert --no-edit <sha>` on v2.3/next, push, PR comment, board rows of the
#         reverted commit's IDs -> blocked, Notes `reverted <sha7>: <reason>`. Never
#         force-pushes.
# batch   vibe/v2.3/batches/<date>-<14|19>-<repo>.md for origin/<base>..origin/v2.3/next
#         (base: android, myitmoapi master; web main, dev after WB-06; backend dev): PRs
#         with item IDs, CI links, diffstat, Roborazzi lines, B migration files, the A
#         githubDebug APK in ~/proj/.wt/run/apk/, open risks; ends with the exact promote
#         command for the owner's "OK <repo> <sha>".
# ready   flips board rows `todo` -> `ready` when every `- needs:` entry of the card
#         (lanes/*.md) is a `merged` card, an `open` gate or owner row, or a recipe whose
#         `- produces:` card is merged; never touches other states; prints unknown IDs
#         (exit 1 when there are any).
#
# Tracked as scripts/integrate.sh (L01 G-13b). ~/proj/.wt/bin/integrate fetches origin
# and runs the copy on origin/v2.3/next. Paths derive from ITMO_WT (default
# ~/proj/.wt; its parent holds the main checkouts), never from $0: guards-test points
# ITMO_WT at its replica. Log: ~/proj/.wt/run/integrate.log.

set -u
PATH="$PATH:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

me=integrate
die() { printf '%s: %s\n' "$me" "$*" >&2; exit 2; }
note() { printf '%s: %s\n' "$me" "$*" >&2; }

WT=$(cd "${ITMO_WT:-$HOME/proj/.wt}" 2>/dev/null && pwd -P) || die "no lane root ${ITMO_WT:-$HOME/proj/.wt}"
PROJ=$(dirname "$WT")
RUN="$WT/run"
VIBE="$PROJ/ITMO.Widgets/vibe/v2.3"
BOARD="$VIBE/board.md"
LANES_DIR="$VIBE/lanes"
BATCHES="$VIBE/batches"
LOG="$RUN/integrate.log"
SIZE_LIMIT=1500
QUEUE_STOP=10
TAB=$(printf '\t')

command -v jq > /dev/null 2>&1 || die "jq is required"

pr_json=""
board=$BOARD

# ---- repositories ------------------------------------------------------------------

repo_info() { # repo -> sets slug letter default main
  case $1 in
    android) slug=alllexey-dev/ITMO.Widgets letter=A default=master main="$PROJ/ITMO.Widgets" ;;
    backend) slug=alllexey-dev/itmo-widgets-backend letter=B default=dev main="$PROJ/itmo-widgets-backend" ;;
    myitmoapi) slug=alllexey-dev/my-itmo-api letter=M default=master main="$PROJ/MyItmoApi" ;;
    web) slug=alllexey-dev/itmo-widgets-web letter=W default=main main="$PROJ/itmo-widgets-web" ;;
    core) die "core has no v2.3/next: L01-CF PRs into core master go to promote" ;;
    *) die "unknown repo '$1' (android, backend, myitmoapi, web)" ;;
  esac
  repo=$1
}

# Master section 6 hot files per repo (globs, see glob_re). Generated files are
# listed too: they are regenerated by the lane, never hand-merged.
hot_globs() {
  case $1 in
    android) cat <<'EOF'
AGENTS.md
CHANGELOG.md
docs/decisions/**
docs/README.md
docs/architecture.md
docs/design.md
docs/recipes/**
docs/product/**
templates/**
settings.gradle.kts
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
gradle/myitmoapi.ref
build-logic/**
app/build.gradle.kts
shared/*/build.gradle.kts
scripts/verify.sh
.github/workflows/android-ci.yml
.github/workflows/android-nightly.yml
.github/workflows/ios.yml
.github/workflows/ios-nightly.yml
**/ArchitectureTest.kt
konsist/**
**/DesignCardResourcesTest.kt
app/src/main/res/values/strings*.xml
app/src/main/res/drawable*/ic_*
**/styles.xml
**/themes.xml
app/src/main/AndroidManifest.xml
app/src/debug/AndroidManifest.xml
**/MainActivity.kt
**/MainNavigationCoordinator.kt
**/core/ui/navigation/AppNavigator.kt
**/app/MainRouteQueue.kt
**/core/navigation/**
app/src/main/res/navigation/*_nav_graph.xml
**/ItmoWidgetsApplication.kt
**/SettingsViewModel.kt
app/src/main/java/dev/alllexey/itmowidgets/di/**
**/testing/Appearances.kt
**/MainNavigationTest.kt
**/StoreScreenshotCapture.kt
**/SiteScreenshotCapture.kt
iosApp/**
shared/**/src/iosMain/**
**/*.xcstrings
shared/backend-client/src/commonTest/resources/contract/**
EOF
      ;;
    backend) cat <<'EOF'
AGENTS.md
build.gradle.kts
src/main/resources/db/migration/**
docs/ops/account-deletion.sql
docs/openapi.json
**/PostgreSqlMigrationTest.kt
**/BackendStartupTest.kt
**/FcmService.kt
**/Device.kt
**/dto/AdminModels.kt
.github/workflows/**
EOF
      ;;
    myitmoapi) cat <<'EOF'
AGENTS.md
pom.xml
kmp/build.gradle.kts
kmp/settings.gradle.kts
.github/workflows/**
EOF
      ;;
    web) cat <<'EOF'
AGENTS.md
site/**
deploy/site.nginx.conf
.github/workflows/**
Dockerfile
EOF
      ;;
  esac
}

# Build files a Dependabot PR may touch and an L04 PR blocks (TC-08 hand-in).
build_globs() {
  cat <<'EOF'
settings.gradle.kts
**/build.gradle.kts
gradle.properties
gradle/libs.versions.toml
gradle/wrapper/**
gradle/gradle-daemon-jvm.properties
build-logic/**
.github/workflows/**
.github/actions/**
EOF
}

# glob -> anchored ERE: `**/` any directories, `**` anything, `*` and `?` within one
# path component; a trailing `/` or a wildcard-free glob also covers what is below it.
glob_re() {
  local g=$1 out="" c i=0 plain=yes
  g=${g#./}
  g=${g#/}
  case $g in *'*'* | *'?'*) plain=no ;; esac
  case $g in */) g="$g**"; plain=no ;; esac
  while [ $i -lt ${#g} ]; do
    c=${g:$i:1}
    if [ "$c" = '*' ]; then
      if [ "${g:$i:2}" = '**' ]; then
        if [ "${g:$((i + 2)):1}" = / ]; then out="$out(.*/)?"; i=$((i + 3)); continue; fi
        out="$out.*"; i=$((i + 2)); continue
      fi
      out="$out[^/]*"
    elif [ "$c" = '?' ]; then
      out="$out[^/]"
    else
      case $c in
        . | '[' | ']' | '\' | '^' | '$' | + | '(' | ')' | '{' | '}' | '|') out="$out\\$c" ;;
        *) out="$out$c" ;;
      esac
    fi
    i=$((i + 1))
  done
  if [ $plain = yes ]; then printf '^%s(/.*)?$' "$out"; else printf '^%s$' "$out"; fi
}

matches_any() { # path globs(newline-separated) -> first matching glob
  local p=$1 g re
  while IFS= read -r g; do
    [ -n "$g" ] || continue
    re=$(glob_re "$g")
    if [[ $p =~ $re ]]; then printf '%s' "$g"; return 0; fi
  done <<EOF
$2
EOF
  return 1
}

# ---- integrator worktree -------------------------------------------------------------

next_dir() {
  local d="$WT/$repo/next" gd
  [ -d "$d" ] || die "integrator worktree $d is missing (lane next $repo)"
  gd=$(git -C "$d" rev-parse --absolute-git-dir 2>/dev/null) || die "$d is not a git worktree"
  [ "$(head -n 1 "$gd/itmo-lane" 2>/dev/null | tr -d ' \t\r')" = integrator ] || die "$d lacks the integrator marker"
  next=$d
}

g() { git -C "$next" "$@"; }

require_clean() {
  local gd dirty
  gd=$(g rev-parse --absolute-git-dir)
  if [ -d "$gd/rebase-merge" ] || [ -d "$gd/rebase-apply" ] || [ -f "$gd/MERGE_HEAD" ] || [ -f "$gd/REVERT_HEAD" ] || [ -f "$gd/CHERRY_PICK_HEAD" ]; then
    die "$next has a rebase, merge, revert or cherry-pick in progress"
  fi
  dirty=$(g status --porcelain) || die "git status failed in $next"
  [ -z "$dirty" ] || die "$next is not clean:
$dirty"
}

fetch_next() {
  g fetch --quiet --prune origin || die "git fetch origin failed in $next"
  nexthead=$(g rev-parse -q --verify "refs/remotes/origin/v2.3/next^{commit}") || die "origin/v2.3/next does not exist in $repo"
}

log_line() { mkdir -p "$RUN" && printf '%s %s %s\n' "$(date +%Y-%m-%dT%H:%M:%S%z)" "$repo" "$*" >> "$LOG"; }

# ---- PR data ---------------------------------------------------------------------------

PR_FIELDS=number,title,body,url,state,headRefName,headRefOid,baseRefName,author,isCrossRepository,isDraft,statusCheckRollup,comments

all_prs() { # -> JSON array of open PRs into v2.3/next
  if [ -n "$pr_json" ]; then
    jq -c '[.[] | select(.baseRefName == "v2.3/next") | select((.state // "OPEN") == "OPEN")]' "$pr_json" || die "cannot read $pr_json"
  else
    gh pr list --repo "$slug" --base v2.3/next --state open --limit 100 --json "$PR_FIELDS" || die "gh pr list failed"
  fi
}

one_pr() { # number -> JSON object (any base, any state)
  if [ -n "$pr_json" ]; then
    jq -c --argjson n "$1" '[.[] | select(.number == $n)] | first // empty' "$pr_json"
  else
    gh pr view "$1" --repo "$slug" --json "$PR_FIELDS"
  fi
}

jf() { printf '%s' "$1" | jq -r "$2"; }

# CI state of a PR head from statusCheckRollup: green | pending | red | none.
ci_state() {
  printf '%s' "$1" | jq -r '
    [ (.statusCheckRollup // [])[]
      | if has("context") or (has("state") and (has("conclusion") | not)) then
          { s: (if ((.state // "") | ascii_upcase) as $x | ($x == "PENDING" or $x == "EXPECTED") then "pending" else "completed" end),
            c: ((.state // "") | ascii_downcase) }
        else
          { s: ((.status // "COMPLETED") | ascii_downcase), c: ((.conclusion // "") | ascii_downcase) }
        end ]
    | if length == 0 then "none"
      elif any(.s != "completed") then "pending"
      elif any(.c as $c | ["success", "skipped", "neutral"] | index($c) | not) then "red"
      elif any(.c == "success") then "green"
      else "none" end'
}

title_ids() { # title -> space-separated IDs, fails when the title is not `<ID>[, <ID>]: <summary>`
  local t=$1 prefix ids="" id
  case $t in *': '*) ;; *) return 1 ;; esac
  prefix=${t%%: *}
  [ -n "${t#*: }" ] || return 1
  local IFS=,
  for id in $prefix; do
    id=$(printf '%s' "$id" | sed 's/^ *//; s/ *$//')
    [[ $id =~ ^[A-Z][A-Z0-9]*(-[A-Za-z0-9.]+)+$ ]] || return 1
    ids="$ids $id"
  done
  [ -n "$ids" ] || return 1
  printf '%s' "${ids# }"
}

surface_of() { # body -> newline-separated globs
  printf '%s\n' "$1" | tr -d '\r' | sed -n 's/^[[:space:]]*\(- \)\{0,1\}Surface:[[:space:]]*//p' | head -n 1 |
    tr ',' '\n' | sed 's/`//g; s/^[[:space:]]*//; s/[[:space:]]*$//' | grep -v -e '^$' -e '^none$' || true
}

body_field() { # body field -> value of the first `<field>:` line
  printf '%s\n' "$1" | tr -d '\r' | sed -n "s/^[[:space:]]*\(- \)\{0,1\}$2:[[:space:]]*//p" | head -n 1
}

is_dependabot() { # pr json
  local h a
  h=$(jf "$1" '.headRefName')
  a=$(jf "$1" '.author.login // ""')
  case $h in dependabot/?*) ;; *) return 1 ;; esac
  case $a in 'dependabot[bot]' | app/dependabot | dependabot) return 0 ;; esac
  return 1
}

is_lane_head() { [[ $1 =~ ^v2\.3/l[0-9][0-9]-[a-z0-9]+(-[a-z0-9]+)*/[a-z0-9][a-z0-9.-]*$ ]]; }

# Changed paths of a head vs origin/v2.3/next (both sides of renames), one per line.
changed_paths() { # sha
  g diff -M --name-status -z "refs/remotes/origin/v2.3/next...$1" | tr '\0' '\n' | awk '
    /^[A-Z][0-9]*$/ { k = substr($0, 1, 1); n = (k == "R" || k == "C") ? 2 : 1; next }
    n > 0 { print; n-- }' | sort -u
}

changed_lines() { # sha -> added + deleted lines, renames counted only for their edits
  g diff -M --numstat "refs/remotes/origin/v2.3/next...$1" | awk -F'\t' '{ if ($1 != "-") s += $1; if ($2 != "-") s += $2 } END { print s + 0 }'
}

head_sha() { # pr json -> sha of origin/<head> (must equal headRefOid)
  local h oid sha
  h=$(jf "$1" '.headRefName')
  oid=$(jf "$1" '.headRefOid')
  sha=$(g rev-parse -q --verify "refs/remotes/origin/$h^{commit}") || { echo ""; return 1; }
  [ "$sha" = "$oid" ] || { echo "$sha"; return 3; }
  echo "$sha"
}

surface_ok_comment() { # pr json
  printf '%s' "$1" | jq -e '[(.comments // [])[] | .body | select(test("^\\s*surface OK"))] | length > 0' > /dev/null
}

# ---- board -------------------------------------------------------------------------------

# board_set <id> <status|-> <branch/pr|-> <note to append|->; 0 when the row exists.
board_set() {
  local tmp="$board.tmp.$$" rc
  [ -f "$board" ] || { note "board $board is missing; skipped $1"; return 1; }
  awk -v id="$1" -v st="$2" -v bp="$3" -v na="$4" '
    function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }
    BEGIN { FS = "|"; found = 0 }
    /^\| / && NF == 9 && trim($2) == id && !found {
      for (i = 2; i <= 8; i++) c[i] = trim($i)
      if (st != "-") c[6] = st
      if (bp != "-") c[7] = bp
      if (na != "-") c[8] = (c[8] == "" ? na : c[8] "; " na)
      line = "|"
      for (i = 2; i <= 8; i++) line = line " " c[i] " |"
      print line
      found = 1
      next
    }
    { print }
    END { exit(found ? 0 : 3) }' "$board" > "$tmp"
  rc=$?
  if [ $rc -eq 0 ]; then
    mv -f "$tmp" "$board" || die "cannot write $board"
    return 0
  fi
  rm -f "$tmp"
  note "board: no row $1 in $board; skipped"
  log_line "board-skip $1"
  return 1
}

# ---- list ----------------------------------------------------------------------------------

cmd_list() {
  [ $# -eq 1 ] || die "usage: integrate list <repo>"
  repo_info "$1"
  next_dir
  fetch_next
  local prs count hot build i pr n title ids ci h sha rc paths surf outside hotfiles size flags p m
  prs=$(all_prs)
  count=$(jf "$prs" 'length')
  hot=$(hot_globs "$repo")
  printf 'queue %s: %s open PR(s) into v2.3/next at %s%s\n' "$repo" "$count" "${nexthead:0:7}" \
    "$([ "$count" -gt $QUEUE_STOP ] && printf ' (above %s: section 4.5 stop, start no new agent)' $QUEUE_STOP)"
  [ "$count" -gt 0 ] || return 0
  printf '%-6s %-22s %-8s %-22s %-8s %s\n' PR ITEMS CI SURFACE LINES 'HOT FILES / FLAGS'
  i=0
  while [ $i -lt "$count" ]; do
    pr=$(printf '%s' "$prs" | jq -c ".[$i]")
    i=$((i + 1))
    n=$(jf "$pr" '.number')
    title=$(jf "$pr" '.title')
    flags=""
    if is_dependabot "$pr"; then ids=dependabot
    else ids=$(title_ids "$title") || { ids='?'; flags="$flags title-not-<ID>"; }
    fi
    ci=$(ci_state "$pr")
    sha=$(head_sha "$pr"); rc=$?
    if [ $rc -ne 0 ] || [ -z "$sha" ]; then
      printf '%-6s %-22s %-8s %-22s %-8s %s\n' "#$n" "${ids// /,}" "$ci" '-' '-' "head $(jf "$pr" '.headRefName') not on origin or moved (fetch, re-run)"
      continue
    fi
    paths=$(changed_paths "$sha")
    size=$(changed_lines "$sha")
    surf=$(surface_of "$(jf "$pr" '.body')")
    outside=0
    hotfiles=""
    if is_dependabot "$pr"; then
      build=$(build_globs)
      while IFS= read -r p; do
        [ -n "$p" ] || continue
        matches_any "$p" "$build" > /dev/null || outside=$((outside + 1))
      done <<EOF
$paths
EOF
    else
      while IFS= read -r p; do
        [ -n "$p" ] || continue
        if [ -z "$surf" ] || ! matches_any "$p" "$surf" > /dev/null; then outside=$((outside + 1)); fi
      done <<EOF
$paths
EOF
    fi
    while IFS= read -r p; do
      [ -n "$p" ] || continue
      m=$(matches_any "$p" "$hot") && hotfiles="$hotfiles $p"
    done <<EOF
$paths
EOF
    if [ -z "$surf" ] && ! is_dependabot "$pr"; then surf="no Surface:"
    elif [ $outside -eq 0 ]; then surf=ok
    else surf="$outside outside"; surface_ok_comment "$pr" && surf="$surf (surface OK)"; fi
    [ "$size" -le $SIZE_LIMIT ] || flags="$flags >${SIZE_LIMIT}-lines"
    [ "$(jf "$pr" '.isDraft // false')" = false ] || flags="$flags draft"
    [ "$(jf "$pr" '.isCrossRepository // false')" = false ] || flags="$flags fork"
    if ! is_dependabot "$pr" && ! is_lane_head "$(jf "$pr" '.headRefName')"; then flags="$flags head-not-v2.3/<lane>/<slug>"; fi
    printf '%-6s %-22s %-8s %-22s %-8s %s\n' "#$n" "${ids// /,}" "$ci" "$surf" "$size" "${hotfiles# }${flags:+ |$flags}"
  done
}

# ---- merge ---------------------------------------------------------------------------------

verify_log_ok() { # log sha7 -> 0 when the last line is a PASS for this repo and sha
  local last re
  [ -f "$1" ] || return 1
  last=$(grep -v '^[[:space:]]*$' "$1" | tail -n 1 | tr -d '\r')
  re="^VERIFY $letter [A-Za-z0-9_-]+ PASS( .*)? $2\$"
  [[ $last =~ $re ]]
}

cmd_merge() {
  [ $# -ge 2 ] || die "usage: integrate merge <repo> <pr> [--local-verify <log>]"
  repo_info "$1"
  local n=$2 local_verify=""
  shift 2
  while [ $# -gt 0 ]; do
    case $1 in
      --local-verify) [ $# -ge 2 ] || die "--local-verify needs a log"; local_verify=$2; shift 2 ;;
      *) die "unknown argument '$1'" ;;
    esac
  done
  [[ $n =~ ^[0-9]+$ ]] || die "PR number must be digits"
  local pr base head title state ids="" dep=no sha rc ci paths p surf outside="" build msg newsha prs i other oh osha body vline
  pr=$(one_pr "$n") || die "cannot load PR #$n"
  [ -n "$pr" ] || die "PR #$n not found"
  state=$(jf "$pr" '.state // "OPEN"')
  [ "$state" = OPEN ] || die "PR #$n is $state"
  base=$(jf "$pr" '.baseRefName')
  case $base in
    v2.3/next) ;;
    release/* | master | main | dev) die "PR #$n targets $base: PRs into release/* or core master go to promote, never to integrate" ;;
    *) die "PR #$n targets $base; integrate merges only into v2.3/next" ;;
  esac
  [ "$(jf "$pr" '.isCrossRepository // false')" = false ] || die "PR #$n comes from a fork"
  [ "$(jf "$pr" '.isDraft // false')" = false ] || die "PR #$n is a draft"
  head=$(jf "$pr" '.headRefName')
  title=$(jf "$pr" '.title')
  if is_dependabot "$pr"; then
    [ "$repo" = android ] || die "Dependabot PRs are merged only in android (TC-08)"
    dep=yes
  else
    is_lane_head "$head" || die "head $head is neither v2.3/<lane>/<slug> nor dependabot/* by dependabot"
    ids=$(title_ids "$title") || die "title '$title' is not '<ID>[, <ID>]: <summary>'"
  fi

  next_dir
  require_clean
  fetch_next
  sha=$(head_sha "$pr"); rc=$?
  [ $rc -ne 3 ] || die "origin/$head is at ${sha:0:7}, the PR data says $(jf "$pr" '.headRefOid' | cut -c1-7): re-run with fresh data"
  [ $rc -eq 0 ] && [ -n "$sha" ] || die "origin/$head does not exist"

  ci=$(ci_state "$pr")
  case $ci in
    green) ;;
    none)
      [ -n "$local_verify" ] || die "PR #$n has no check runs: pass --local-verify <log> of your own verify ending 'VERIFY $letter <mode> PASS ... ${sha:0:7}'"
      verify_log_ok "$local_verify" "${sha:0:7}" || die "the last line of $local_verify is not 'VERIFY $letter <mode> PASS ... ${sha:0:7}'"
      body=$(jf "$pr" '.body // ""')
      vline=$(body_field "$body" Verify)
      if [ $dep = no ]; then
        case $vline in *PASS*) ;; *) die "PR #$n has no check runs and its body has no PASS 'Verify:' line (got: ${vline:-none})" ;; esac
      fi
      ci="local: $(grep -v '^[[:space:]]*$' "$local_verify" | tail -n 1)"
      ;;
    *) die "PR #$n head ${sha:0:7} CI is $ci, not green" ;;
  esac

  paths=$(changed_paths "$sha")
  [ -n "$paths" ] || die "PR #$n changes nothing against origin/v2.3/next"
  if [ $dep = yes ]; then
    build=$(build_globs)
    while IFS= read -r p; do
      [ -n "$p" ] || continue
      matches_any "$p" "$build" > /dev/null || outside="$outside $p"
    done <<EOF
$paths
EOF
    [ -z "$outside" ] || die "Dependabot PR #$n touches non-build files:$outside"
    prs=$(all_prs)
    i=0
    while [ $i -lt "$(jf "$prs" 'length')" ]; do
      other=$(printf '%s' "$prs" | jq -c ".[$i]")
      i=$((i + 1))
      oh=$(jf "$other" '.headRefName')
      case $oh in v2.3/l04-toolchain/*) ;; *) continue ;; esac
      osha=$(g rev-parse -q --verify "refs/remotes/origin/$oh^{commit}") || die "cannot resolve origin/$oh of open L04 PR #$(jf "$other" '.number')"
      while IFS= read -r p; do
        [ -n "$p" ] || continue
        if matches_any "$p" "$build" > /dev/null; then
          die "L04 build-file PR #$(jf "$other" '.number') ($oh, $p) is open: Dependabot PR #$n waits"
        fi
      done <<EOF
$(changed_paths "$osha")
EOF
    done
    msg="TC-08: $title (#$n)"
  else
    surf=$(surface_of "$(jf "$pr" '.body // ""')")
    while IFS= read -r p; do
      [ -n "$p" ] || continue
      if [ -z "$surf" ] || ! matches_any "$p" "$surf" > /dev/null; then outside="$outside $p"; fi
    done <<EOF
$paths
EOF
    if [ -n "$outside" ]; then
      surface_ok_comment "$pr" || die "PR #$n touches paths outside its Surface: (${surf:-none}):$outside; comment \"surface OK\" to accept"
      note "paths outside Surface: accepted by a 'surface OK' comment:$outside"
    fi
    msg="$title (#$n)"
  fi
  local size
  size=$(changed_lines "$sha")
  [ "$size" -le $SIZE_LIMIT ] || note "warning: PR #$n changes $size lines (> $SIZE_LIMIT; renames aside)"

  g checkout --quiet --detach "$nexthead" || die "checkout of origin/v2.3/next failed"
  if ! g merge --squash --quiet "$sha" > /dev/null 2>&1; then
    g reset --quiet --hard "$nexthead"
    [ -z "$(g status --porcelain)" ] || note "warning: $next is not clean after the aborted squash"
    gh pr comment "$n" --repo "$slug" --body "rebase on v2.3/next (conflict with ${nexthead:0:7})" > /dev/null || note "warning: gh pr comment failed"
    log_line "conflict #$n ${sha:0:7} on ${nexthead:0:7}"
    note "conflict: PR #$n stays open, asked to rebase on v2.3/next"
    exit 1
  fi
  if g diff --cached --quiet; then
    g reset --quiet --hard "$nexthead"
    die "PR #$n adds nothing on top of origin/v2.3/next"
  fi
  g commit --quiet -m "$msg" > /dev/null || { g reset --quiet --hard "$nexthead"; die "commit failed"; }
  newsha=$(g rev-parse HEAD)
  if ! g push --quiet origin "HEAD:refs/heads/v2.3/next"; then
    g reset --quiet --hard "$nexthead"
    die "push of v2.3/next failed (see the guard output); nothing merged"
  fi
  log_line "merged #$n ${sha:0:7} as ${newsha:0:7} ci=$(printf '%s' "$ci" | tr ' ' '_') msg=$msg"
  gh pr close "$n" --repo "$slug" --comment "Squash-merged into v2.3/next as $newsha" > /dev/null ||
    note "warning: gh pr close failed; close #$n by hand with: Squash-merged into v2.3/next as $newsha"
  local id
  for id in $ids; do
    board_set "$id" merged "$letter#$n ${newsha:0:7}" - && note "board: $id -> merged"
  done
  printf 'merged #%s as %s: %s\n' "$n" "$newsha" "$msg"
}

# ---- revert --------------------------------------------------------------------------------

cmd_revert() {
  [ $# -eq 3 ] || die "usage: integrate revert <repo> <sha> <reason>"
  repo_info "$1"
  local arg=$2 reason sha subject n="" ids="" newsha pr skip_board=no id
  reason=$(printf '%s' "$3" | tr '|\n\r' '/  ')
  [ -n "$reason" ] || die "a reason is required"
  [[ $arg =~ ^[0-9a-f]{7,40}$ ]] || die "sha must be 7-40 lowercase hex digits"
  next_dir
  require_clean
  fetch_next
  sha=$(g rev-parse -q --verify "$arg^{commit}") || die "$arg is not a commit"
  g merge-base --is-ancestor "$sha" "$nexthead" || die "${sha:0:7} is not on origin/v2.3/next"
  subject=$(g log -1 --format=%s "$sha")
  if [[ $subject =~ \(#([0-9]+)\)$ ]]; then n=${BASH_REMATCH[1]}; fi
  ids=$(title_ids "${subject% (#*)}") || ids=""
  if [ -n "$n" ]; then
    pr=$(one_pr "$n" 2>/dev/null) || pr=""
    if [ -n "$pr" ] && is_dependabot "$pr"; then skip_board=yes; fi
  fi
  g checkout --quiet --detach "$nexthead" || die "checkout of origin/v2.3/next failed"
  if ! g revert --no-edit "$sha" > /dev/null 2>&1; then
    g revert --abort > /dev/null 2>&1 || g reset --quiet --hard "$nexthead"
    die "git revert of ${sha:0:7} conflicts with later commits; revert them first or ask the lane"
  fi
  newsha=$(g rev-parse HEAD)
  if ! g push --quiet origin "HEAD:refs/heads/v2.3/next"; then
    g reset --quiet --hard "$nexthead"
    die "push of the revert failed (see the guard output)"
  fi
  log_line "reverted ${sha:0:7} as ${newsha:0:7} reason=$reason"
  if [ -n "$n" ]; then
    gh pr comment "$n" --repo "$slug" --body "Reverted on v2.3/next as $newsha: $reason" > /dev/null || note "warning: gh pr comment failed on #$n"
  else
    note "no (#<n>) in '$subject': no PR comment"
  fi
  if [ $skip_board = no ]; then
    for id in $ids; do
      board_set "$id" blocked - "reverted ${sha:0:7}: $reason" && note "board: $id -> blocked"
    done
  fi
  printf 'reverted %s as %s\n' "$sha" "$newsha"
}

# ---- batch ---------------------------------------------------------------------------------

batch_base() {
  case $repo in
    web)
      if g cat-file -e "refs/remotes/origin/main:.github/workflows/deliver.yml" 2>/dev/null &&
        g rev-parse -q --verify refs/remotes/origin/dev > /dev/null; then
        printf dev
      else printf main; fi
      ;;
    *) printf '%s' "$default" ;;
  esac
}

head_checks() { # sha -> green | pending | red | none (check runs via gh api)
  local runs total=0 ok=0 bad=no name status conclusion
  runs=$(gh api "repos/$slug/commits/$1/check-runs?per_page=100" \
    --jq '.check_runs[] | [.name, .status, (.conclusion // "none")] | @tsv' 2>/dev/null) || { printf unknown; return; }
  while IFS="$TAB" read -r name status conclusion; do
    [ -n "$name" ] || continue
    total=$((total + 1))
    if [ "$status" != completed ]; then bad=pending; continue; fi
    case $conclusion in success) ok=$((ok + 1)) ;; skipped | neutral) ;; *) [ $bad = pending ] || bad=red ;; esac
  done <<EOF
$runs
EOF
  if [ $total -eq 0 ]; then printf none
  elif [ $bad != no ]; then printf '%s' "$bad"
  elif [ $ok -ge 1 ]; then printf green
  else printf none; fi
}

cmd_batch() {
  [ $# -ge 1 ] || die "usage: integrate batch <repo> [--window 14|19] [--apk <file> | --build-apk]"
  repo_info "$1"
  shift
  local window="" apk="" build_apk=no
  while [ $# -gt 0 ]; do
    case $1 in
      --window) [ $# -ge 2 ] || die "--window needs 14 or 19"; window=$2; shift 2 ;;
      --apk) [ $# -ge 2 ] || die "--apk needs a file"; apk=$2; shift 2 ;;
      --build-apk) build_apk=yes; shift ;;
      *) die "unknown argument '$1'" ;;
    esac
  done
  if [ -z "$window" ]; then
    if [ "$(date +%H)" -lt 17 ]; then window=14; else window=19; fi
  fi
  case $window in 14 | 19) ;; *) die "--window is 14 or 19" ;; esac
  [ -z "$apk" ] || [ "$repo" = android ] || die "--apk applies to android"
  [ "$build_apk" = no ] || [ "$repo" = android ] || die "--build-apk applies to android"

  next_dir
  fetch_next
  local baseref basesha file commits count head7 hc
  baseref=$(batch_base)
  basesha=$(g rev-parse -q --verify "refs/remotes/origin/$baseref^{commit}") || die "origin/$baseref does not exist"
  commits=$(g log --reverse --first-parent --format="%H$TAB%s" "$basesha..$nexthead")
  if [ -z "$commits" ]; then
    printf 'nothing to batch: origin/v2.3/next = origin/%s (%s)\n' "$baseref" "${basesha:0:7}"
    return 0
  fi
  g merge-base --is-ancestor "$basesha" "$nexthead" || die "origin/v2.3/next does not contain origin/$baseref: promote would not fast-forward"
  count=$(printf '%s\n' "$commits" | wc -l | tr -d ' ')
  head7=${nexthead:0:7}
  mkdir -p "$BATCHES" || die "cannot create $BATCHES"
  file="$BATCHES/$(date +%Y-%m-%d)-$window-$repo.md"
  [ ! -e "$file" ] || die "$file already exists (it may hold the owner's verdict); pass the other --window or edit it"

  # APK (android): copied from --apk, or built in the android slot with --build-apk.
  local apk_line="not built (integrate batch android --build-apk, or --apk <file>)"
  if [ "$repo" = android ] && { [ -n "$apk" ] || [ $build_apk = yes ]; }; then
    if [ $build_apk = yes ]; then
      require_clean
      g checkout --quiet --detach "$nexthead" || die "checkout of origin/v2.3/next failed"
      # The bin copy of the merged scripts/slot.sh (TC-12), else the checkout's own copy;
      # slot.sh sets ANDROID_HOME and JAVA_HOME (JDK 21) when they are unset.
      local slot_sh=${ITMO_SLOT_SH:-$WT/bin/slot.sh}
      [ -x "$slot_sh" ] || slot_sh="$next/scripts/slot.sh"
      [ -x "$slot_sh" ] || die "no slot script at $WT/bin/slot.sh or $next/scripts/slot.sh"
      (cd "$next" && "$slot_sh" android -- ./gradlew --quiet :app:assembleGithubDebug) ||
        die "assembleGithubDebug failed on $head7"
      apk=$(ls "$next"/app/build/outputs/apk/github/debug/*.apk 2>/dev/null | head -n 1)
      [ -n "$apk" ] || die "no githubDebug APK under $next/app/build/outputs/apk/github/debug"
    fi
    [ -f "$apk" ] || die "APK $apk does not exist"
    mkdir -p "$RUN/apk" || die "cannot create $RUN/apk"
    cp -f "$apk" "$RUN/apk/android-$head7-githubDebug.apk" || die "cannot copy $apk"
    apk_line="\`$RUN/apk/android-$head7-githubDebug.apk\` (githubDebug of $head7)"
  fi

  hc=$(head_checks "$nexthead")
  local risks="" line sha subject n ids pr body url robo rev stable ci shortstat hotfiles p hot mig promote_cmd
  hot=$(hot_globs "$repo")
  {
    printf '# Batch %s %s %s: %s..%s\n\n' "$repo" "$(date +%Y-%m-%d)" "$window:00" "${basesha:0:7}" "$head7"
    printf -- '- Range: `origin/%s..origin/v2.3/next` = `%s..%s`, %s commit(s)\n' "$baseref" "${basesha:0:7}" "$head7" "$count"
    printf -- '- Batch head: `%s`, CI %s (https://github.com/%s/commit/%s/checks)\n' "$nexthead" "$hc" "$slug" "$nexthead"
    printf -- '- Diffstat: %s\n' "$(g diff --shortstat "$basesha" "$nexthead" | sed 's/^ *//')"
    [ "$repo" != android ] || printf -- '- APK: %s\n' "$apk_line"
    printf '\n## Pull requests\n\n'
    printf '| Commit | PR | Items | CI | Diffstat | Roborazzi | Hot files |\n|---|---|---|---|---|---|---|\n'
  } > "$file"
  while IFS="$TAB" read -r sha subject; do
    [ -n "$sha" ] || continue
    n="" ids="" url="" robo="-" ci="-" body=""
    if [[ $subject =~ \(#([0-9]+)\)$ ]]; then n=${BASH_REMATCH[1]}; fi
    ids=$(title_ids "${subject% (#*)}") || ids="?"
    ids=${ids// /, }
    if [[ $subject =~ ^Revert\ \".*\(#([0-9]+)\)\"$ ]]; then
      ids="revert of #${BASH_REMATCH[1]}"
      url="https://github.com/$slug/pull/${BASH_REMATCH[1]}"
      risks="$risks
- #${BASH_REMATCH[1]} was reverted on v2.3/next by ${sha:0:7}: its board rows are blocked"
    fi
    if [ -n "$n" ]; then
      url="https://github.com/$slug/pull/$n"
      pr=$(one_pr "$n" 2>/dev/null) || pr=""
      if [ -n "$pr" ]; then
        body=$(jf "$pr" '.body // ""')
        robo=$(body_field "$body" 'Roborazzi diff')
        [ -n "$robo" ] || robo="-"
        ci="$(ci_state "$pr") ($url/checks)"
        rev=$(body_field "$body" 'Revertable alone')
        case $rev in no*) risks="$risks
- #$n not revertable alone: ${rev#no}" ;; esac
        stable=$(body_field "$body" 'Stable identifiers touched')
        case $stable in '' | none | None) ;; *) risks="$risks
- #$n touches stable identifiers: $stable (SS-01 must be green on the batch head)" ;; esac
        case $ci in green*) ;; *) risks="$risks
- #$n head CI was ${ci%% *} at merge time" ;; esac
      else
        ci="PR data unavailable"
      fi
    fi
    shortstat=$(g show --shortstat --format= "$sha" | grep . | sed 's/^ *//; s/ files\{0,1\} changed/f/; s/ insertions\{0,1\}(+)/+/; s/ deletions\{0,1\}(-)/-/')
    hotfiles=""
    while IFS= read -r p; do
      [ -n "$p" ] || continue
      matches_any "$p" "$hot" > /dev/null && hotfiles="$hotfiles \`$p\`"
    done <<EOF
$(g show --name-only --format= "$sha")
EOF
    printf '| `%s` %s | %s | %s | %s | %s | %s | %s |\n' "${sha:0:7}" "$(printf '%s' "$subject" | tr '|' '/')" \
      "${url:-none}" "$ids" "$ci" "$shortstat" "$(printf '%s' "$robo" | tr '|' '/')" "${hotfiles# }" >> "$file"
  done <<EOF
$commits
EOF
  if [ "$repo" = backend ]; then
    mig=$(g diff --name-status "$basesha" "$nexthead" -- src/main/resources/db/migration/ | tr '\t' ' ')
    {
      printf '\n## Migrations (B)\n\n'
      if [ -n "$mig" ]; then printf '%s\n' "$mig" | sed 's/^/- /'; else printf 'none\n'; fi
    } >> "$file"
    if printf '%s\n' "$mig" | grep -qv '^A '; then
      [ -z "$mig" ] || risks="$risks
- a merged migration is modified or deleted (expand-only, never edit a merged migration)"
    fi
  fi
  case $hc in green) ;; *) risks="$risks
- batch head CI: $hc" ;; esac
  case $repo in
    android) promote_cmd="$WT/bin/promote android master $nexthead" ;;
    backend) promote_cmd="$WT/bin/promote backend dev $nexthead --deploy-dev" ;;
    myitmoapi) promote_cmd="$WT/bin/promote myitmoapi master $nexthead" ;;
    web) if [ "$baseref" = dev ]; then promote_cmd="$WT/bin/promote web dev $nexthead --deploy-dev"; else promote_cmd="$WT/bin/promote web main $nexthead"; fi ;;
  esac
  [ "$hc" != none ] || promote_cmd="$promote_cmd --local-verify $RUN/verify-$repo-$head7.log"
  {
    printf '\n## Open risks\n\n'
    if [ -n "$risks" ]; then printf '%s\n' "${risks#?}"; else printf 'none found by integrate; add the integrator'\''s own\n'; fi
    printf '\n## Batch-head verify\n\n'
    case $repo in
      android) printf '`verify.sh full`, `ANDROID_SERIAL=emulator-5554 verify.sh ui @platform`, `ios-check` (before verify.sh exists: the AGENTS.md command under the android slot lock); log the last line to `%s`.\n' "$RUN/verify-$repo-$head7.log" ;;
      *) printf '`scripts/verify.sh` (before it exists: the AGENTS.md command under the slot lock); log the last line to `%s`.\n' "$RUN/verify-$repo-$head7.log" ;;
    esac
    printf '\n## Promote\n\n'
    case $repo in
      backend) printf 'After the owner'\''s "OK backend %s" and "deploy dev" (at most once a day); `deliver.yml` then moves `master`:\n\n' "$head7" ;;
      web) if [ "$baseref" = dev ]; then printf 'After the owner'\''s "OK web %s" and "deploy dev"; `deliver` then moves `main`:\n\n' "$head7"; else printf 'After the owner'\''s "OK web %s":\n\n' "$head7"; fi ;;
      *) printf 'After the owner'\''s "OK %s %s":\n\n' "$repo" "$head7" ;;
    esac
    printf '    %s\n' "$promote_cmd"
  } >> "$file"
  log_line "batch $file ${basesha:0:7}..$head7 commits=$count"
  printf '%s\n' "$file"
}

# ---- ready ---------------------------------------------------------------------------------

cmd_ready() {
  local dry=no lanes=$LANES_DIR tmp rep rc
  while [ $# -gt 0 ]; do
    case $1 in
      --dry-run) dry=yes; shift ;;
      --lanes) [ $# -ge 2 ] || die "--lanes needs a directory"; lanes=$2; shift 2 ;;
      *) die "unknown argument '$1'" ;;
    esac
  done
  [ -f "$board" ] || die "board $board does not exist"
  ls "$lanes"/*.md > /dev/null 2>&1 || die "no lane files in $lanes"
  tmp="$board.tmp.$$"
  rep="$board.report.$$"
  awk -v board="$board" -v rep="$rep" '
    function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }
    function unknown(tok, where) { if (!((tok SUBSEP where) in seenu)) { seenu[tok SUBSEP where] = 1; nu++; ulist[nu] = tok " (" where ")" } }
    BEGIN {
      FS = "|"
      while ((getline line < board) > 0) {
        if (line !~ /^\| / || split(line, f, "|") != 9) continue
        id = trim(f[2]); if (id == "Card") continue
        status[id] = trim(f[6]); lane[id] = trim(f[3]); rows[++nr] = id
      }
      close(board)
      FS = " "
    }
    /^#/ { cur = ""; if ($0 ~ /^### .+ · /) { h = $0; sub(/^### /, "", h); sub(/ · .*/, "", h); cur = trim(h); card[cur] = FILENAME; ncards++ } ; next }
    cur != "" && /^- needs:/ && !(cur in needs) { s = $0; sub(/^- needs:/, "", s); needs[cur] = s; next }
    cur != "" && /^- produces:/ {
      s = $0; sub(/^- produces:/, "", s); n = split(s, p, ",")
      for (i = 1; i <= n; i++) { t = trim(p[i]); if (t ~ /^recipe:/) { if (t in producer) dup[t] = 1; producer[t] = cur } }
      next
    }
    END {
      for (c in card) if (!(c in status)) unknown(c, "card in " card[c] " without a board row")
      for (k = 1; k <= nr; k++) { id = rows[k]; if (lane[id] != "gate" && lane[id] != "owner" && !(id in card)) unknown(id, "board row without a lane card") }
      for (t in dup) unknown(t, "produced by two cards")
      for (c in card) {
        if (!(c in needs)) { unknown(c, "card without a - needs: line"); continue }
        n = split(needs[c], p, ","); ok = 1
        for (i = 1; i <= n; i++) {
          t = trim(p[i]); if (t == "" || t == "-") continue
          if (t ~ /^recipe:/) {
            if (!(t in producer)) { unknown(t, "need of " c); ok = 0; continue }
            q = producer[t]
            if (!(q in status)) { unknown(q, "producer of " t); ok = 0; continue }
            if (status[q] != "merged") ok = 0
          } else if (t in status) {
            if (lane[t] == "gate" || lane[t] == "owner") { if (status[t] != "open") ok = 0 }
            else if (status[t] != "merged") ok = 0
          } else { unknown(t, "need of " c); ok = 0 }
        }
        sat[c] = ok
      }
      flipped = ""; nf = 0; nready = 0; stale = ""
      FS = "|"
      while ((getline line < board) > 0) {
        if (line ~ /^\| / && split(line, f, "|") == 9) {
          id = trim(f[2])
          if (status[id] == "todo" && (id in sat) && sat[id]) {
            out = "|"
            for (i = 2; i <= 8; i++) { v = trim(f[i]); if (i == 6) v = "ready"; out = out " " v " |" }
            print out; nf++; flipped = flipped " " id; nready++; continue
          }
          if (status[id] == "ready") { nready++; if ((id in sat) && !sat[id]) stale = stale " " id }
        }
        print line
      }
      close(board)
      printf "flipped %d todo -> ready:%s\n", nf, flipped > rep
      printf "ready rows now: %d\n", nready > rep
      if (stale != "") printf "ready rows with unmet needs (left as they are):%s\n", stale > rep
      printf "cards in lane files: %d; unknown IDs: %d\n", ncards, nu > rep
      for (k = 1; k <= nu; k++) printf "unknown: %s\n", ulist[k] > rep
      exit(nu > 0 ? 1 : 0)
    }' "$lanes"/*.md > "$tmp"
  rc=$?
  [ -s "$tmp" ] || { rm -f "$tmp" "$rep"; die "board parse produced nothing"; }
  cat "$rep"
  rm -f "$rep"
  if [ $dry = yes ]; then
    rm -f "$tmp"
    note "dry run: $board unchanged"
  else
    mv -f "$tmp" "$board" || die "cannot write $board"
  fi
  return $rc
}

# ---- main ------------------------------------------------------------------------------------

args=()
while [ $# -gt 0 ]; do
  case $1 in
    --pr-json) [ $# -ge 2 ] || die "--pr-json needs a file"; pr_json=$2; [ -f "$pr_json" ] || die "$pr_json does not exist"; shift 2 ;;
    --board) [ $# -ge 2 ] || die "--board needs a file"; board=$2; shift 2 ;;
    *) args+=("$1"); shift ;;
  esac
done
[ ${#args[@]} -ge 1 ] || die "usage: integrate list|merge|revert|batch|ready ... (integrate --help)"
cmd=${args[0]}
rest=("${args[@]:1}")
case $cmd in
  list) cmd_list ${rest[@]+"${rest[@]}"} ;;
  merge) cmd_merge ${rest[@]+"${rest[@]}"} ;;
  revert) cmd_revert ${rest[@]+"${rest[@]}"} ;;
  batch) cmd_batch ${rest[@]+"${rest[@]}"} ;;
  ready) cmd_ready ${rest[@]+"${rest[@]}"} ;;
  -h | --help | help) awk 'NR > 1 && !/^#/ { exit } NR > 1' "$0" ;;
  *) die "unknown command '$cmd' (list, merge, revert, batch, ready)" ;;
esac
