// Generated by itmowidgets.strings from the androidExport files of the shared modules; do not edit.
package dev.alllexey.itmowidgets.core.ui

import dev.alllexey.itmowidgets.R

/** `StringResource.key` -> `R.string` and `PluralStringResource.key` -> `R.plurals` (ADR 0028). */
internal object ExportedStringIds {

    fun string(key: String): Int = when (key) {
        "common_retry" -> R.string.common_retry
        else -> throw IllegalArgumentException(
            "No exported string \"$key\"; is its file named in an androidExport line?"
        )
    }

    fun plural(key: String): Int = when (key) {
        "common_days" -> R.plurals.common_days
        else -> throw IllegalArgumentException(
            "No exported plurals \"$key\"; is its file named in an androidExport line?"
        )
    }
}
